package com.myspace.employee_rostering;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Shift implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.myspace.employee_rostering.Timeslot timeslot;
	private com.myspace.employee_rostering.Skill requiredSkill;

	public Shift() {
	}

	public com.myspace.employee_rostering.Timeslot getTimeslot() {
		return this.timeslot;
	}

	public void setTimeslot(com.myspace.employee_rostering.Timeslot timeslot) {
		this.timeslot = timeslot;
	}

	public com.myspace.employee_rostering.Skill getRequiredSkill() {
		return this.requiredSkill;
	}

	public void setRequiredSkill(
			com.myspace.employee_rostering.Skill requiredSkill) {
		this.requiredSkill = requiredSkill;
	}

	public Shift(com.myspace.employee_rostering.Timeslot timeslot,
			com.myspace.employee_rostering.Skill requiredSkill) {
		this.timeslot = timeslot;
		this.requiredSkill = requiredSkill;
	}

}